'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { api, Monitor, PaginationMeta, Service } from '@/lib/api';
import { supabase } from '@/lib/supabase';

const emptyMeta: PaginationMeta = { page: 1, limit: 10, total: 0, totalPages: 0 };
type Filter = 'ALL' | 'UP' | 'DOWN' | 'PAUSED';

export default function MonitorsPage() {
  const [items, setItems] = useState<Monitor[]>([]); const [services, setServices] = useState<Service[]>([]); const [meta, setMeta] = useState(emptyMeta); const [page, setPage] = useState(1); const [search, setSearch] = useState(''); const [serviceId, setServiceId] = useState(''); const [status, setStatus] = useState<Filter>('ALL'); const [name, setName] = useState(''); const [url, setUrl] = useState(''); const [createService, setCreateService] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { try { const [monitors, serviceData] = await Promise.all([api.monitors.list({ page, limit: 10, search: search || undefined, serviceId: serviceId || undefined, status: status === 'ALL' ? undefined : status }), api.services.list({ page: 1, limit: 50 })]); setItems(monitors.data); setMeta(monitors.meta); setServices(serviceData.data); if (!createService && serviceData.data[0]) setCreateService(serviceData.data[0].id); setError(''); } catch (err) { setError(err instanceof Error ? err.message : 'Impossible de charger les monitors.'); } }, [page, search, serviceId, status, createService]);
  useEffect(() => { supabase.auth.getUser().then(({ data }) => { if (!data.user) window.location.href = '/login'; else void load(); }); }, [load]);
  async function create(event: FormEvent) { event.preventDefault(); if (!createService || !name.trim() || !url.trim()) return; setBusy(true); setError(''); try { await api.monitors.create({ serviceId: createService, name: name.trim(), url: url.trim(), interval: 60, timeout: 10000, expectedStatus: 200 }); setName(''); setUrl(''); setPage(1); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Création impossible.'); } finally { setBusy(false); } }
  async function toggle(item: Monitor) { try { if (item.isActive) await api.monitors.deactivate(item.id); else await api.monitors.activate(item.id); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Modification impossible.'); } }
  async function remove(item: Monitor) { if (!window.confirm(`Supprimer « ${item.name} » ?`)) return; try { await api.monitors.remove(item.id); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Suppression impossible.'); } }
  const dot = (item: Monitor) => !item.isActive ? 'bg-[var(--solar)]' : item.latestCheck?.status === 'DOWN' ? 'bg-[var(--flare)]' : 'bg-[var(--volt)]';
  return <div className="mx-auto max-w-6xl px-4 py-7 sm:px-6 sm:py-10 lg:px-8"><div className="mb-7"><p className="data-mono text-xs uppercase tracking-[0.18em] text-[var(--electric)]">Workspace / Monitors</p><h1 className="mt-2 text-3xl font-bold">Monitors</h1><p className="mt-2 text-sm text-white/45">Recherchez, filtrez et pilotez tous vos endpoints depuis un seul endroit.</p></div>{error && <div className="mb-5 rounded-xl border border-[var(--flare)]/20 bg-[var(--flare)]/10 px-4 py-3 text-sm text-[var(--flare)]">{error}</div>}
    <section className="rounded-2xl border border-white/[0.07] bg-white/[0.025] p-5 sm:p-6"><p className="data-mono text-xs uppercase tracking-[0.15em] text-white/30">Nouveau monitor</p><form onSubmit={create} className="mt-4 grid gap-3 md:grid-cols-[180px_1fr_1.5fr_auto]"><select required value={createService} onChange={(e) => setCreateService(e.target.value)} className="auth-input"><option value="" disabled>Sélectionner un service…</option>{services.map((service) => <option key={service.id} value={service.id}>{service.name}</option>)}</select><input required value={name} onChange={(e) => setName(e.target.value)} placeholder="Nom du monitor" className="auth-input" /><input required type="url" value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://api.exemple.com/health" className="auth-input" /><button disabled={busy || !createService} className="auth-button md:w-auto">{busy ? 'Ajout…' : 'Ajouter'}</button></form></section>
    <section className="mt-5 rounded-2xl border border-white/[0.07] bg-white/[0.025] p-5 sm:p-6"><div className="grid gap-3 lg:grid-cols-[1fr_190px_170px]"><SearchInput value={search} onChange={(v) => { setSearch(v); setPage(1); }} placeholder="Rechercher nom ou URL…" /><select value={serviceId} onChange={(e) => { setServiceId(e.target.value); setPage(1); }} className="auth-input"><option value="">Tous les services</option>{services.map((service) => <option key={service.id} value={service.id}>{service.name}</option>)}</select><select value={status} onChange={(e) => { setStatus(e.target.value as Filter); setPage(1); }} className="auth-input"><option value="ALL">Tous les statuts</option><option value="UP">UP</option><option value="DOWN">DOWN</option><option value="PAUSED">En pause</option></select></div><div className="mt-5 space-y-2">{items.map((item) => <Link href={`/dashboard/monitors/${item.id}`} key={item.id} className="block rounded-xl border border-white/[0.07] bg-[var(--ink)] p-4 transition hover:border-[var(--electric)]/25"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex items-center gap-3"><span className={`h-2.5 w-2.5 shrink-0 rounded-full ${dot(item)}`} /><div><h3 className="font-semibold">{item.name}</h3><p className="data-mono mt-1 break-all text-xs text-white/35">{item.url}</p></div></div></div><div className="flex flex-wrap items-center gap-2"><span className="data-mono rounded-md bg-white/[0.04] px-2 py-1 text-[10px] text-white/40">GET · {item.interval}s</span><span className="data-mono text-[10px] text-white/35">{!item.isActive ? 'PAUSED' : item.latestCheck?.status ?? 'NO CHECK'}</span><button type="button" onClick={(event) => { event.preventDefault(); void toggle(item); }} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-white/65 hover:text-white">{item.isActive ? 'Pause' : 'Activer'}</button><button type="button" onClick={(event) => { event.preventDefault(); void remove(item); }} className="rounded-lg border border-[var(--flare)]/15 px-3 py-2 text-xs text-[var(--flare)] hover:bg-[var(--flare)]/10">Supprimer</button></div></div></Link>)}{!items.length && <p className="py-10 text-center text-sm text-white/30">Aucun monitor trouvé.</p>}</div><Pagination meta={meta} page={page} setPage={setPage} /></section></div>;
}
function SearchInput({ value, onChange, placeholder }: { value: string; onChange: (value: string) => void; placeholder: string }) { return <div className="relative"><span className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-white/35" aria-hidden="true">⌕</span><input value={value} onChange={(e) => onChange(e.target.value)} placeholder={placeholder} className="auth-input pl-12" /></div>; }
function Pagination({ meta, page, setPage }: { meta: PaginationMeta; page: number; setPage: (page: number) => void }) { if (meta.totalPages <= 1) return null; return <div className="mt-5 flex items-center justify-between border-t border-white/[0.06] pt-4"><span className="data-mono text-[10px] text-white/30">Page {page} / {meta.totalPages}</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => setPage(page - 1)} className="rounded-lg border border-white/10 px-3 py-2 text-xs disabled:opacity-30">←</button><button disabled={page >= meta.totalPages} onClick={() => setPage(page + 1)} className="rounded-lg border border-white/10 px-3 py-2 text-xs disabled:opacity-30">→</button></div></div>; }
