'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { api, Monitor, PaginationMeta, Service } from '@/lib/api';
import { supabase } from '@/lib/supabase';

const emptyMeta: PaginationMeta = { page: 1, limit: 10, total: 0, totalPages: 0 };
type Filter = 'ALL' | 'UP' | 'DOWN' | 'PAUSED';
const intervalOptions = [
  { value: 60, label: '1 minute', hint: 'Surveillance critique' },
  { value: 300, label: '5 minutes', hint: 'Équilibre recommandé' },
  { value: 600, label: '10 minutes', hint: 'API moins critique' },
  { value: 900, label: '15 minutes', hint: 'Surveillance légère' },
  { value: 1800, label: '30 minutes', hint: 'Disponibilité générale' },
  { value: 3600, label: '1 heure', hint: 'Disponibilité générale — faible fréquence' },
];

function formatInterval(seconds: number) {
  if (seconds < 60) return `${seconds}s`;
  const minutes = seconds / 60;
  return minutes >= 60 ? `${minutes / 60}h` : `${minutes} min`;
}

function ConfirmDialog({ item, busy, onCancel, onConfirm }: { item: Monitor; busy: boolean; onCancel: () => void; onConfirm: () => void }) {
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 px-4 backdrop-blur-sm" role="dialog" aria-modal="true"><div className="w-full max-w-md rounded-2xl border border-white/[0.09] bg-[#0B0F1A] p-6 shadow-2xl"><p className="data-mono text-xs uppercase tracking-[0.16em] text-[var(--flare)]">Confirmation</p><h2 className="mt-2 text-xl font-semibold">Supprimer « {item.name} » ?</h2><p className="mt-3 text-sm leading-6 text-white/50">Cette action supprimera ce monitor et son historique de checks. Elle est irréversible.</p><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onCancel} disabled={busy} className="rounded-lg border border-white/10 px-4 py-2 text-sm text-white/60 hover:text-white disabled:opacity-40">Annuler</button><button type="button" onClick={onConfirm} disabled={busy} className="rounded-lg bg-[var(--flare)] px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">{busy ? 'Suppression…' : 'Supprimer'}</button></div></div></div>;
}

export default function MonitorsPage() {
  const [items, setItems] = useState<Monitor[]>([]); const [services, setServices] = useState<Service[]>([]); const [meta, setMeta] = useState(emptyMeta); const [page, setPage] = useState(1); const [search, setSearch] = useState(''); const [serviceId, setServiceId] = useState(''); const [status, setStatus] = useState<Filter>('ALL'); const [name, setName] = useState(''); const [url, setUrl] = useState(''); const [interval, setInterval] = useState(300); const [createService, setCreateService] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [confirm, setConfirm] = useState<Monitor | null>(null);
  const load = useCallback(async () => { try { const [monitors, serviceData] = await Promise.all([api.monitors.list({ page, limit: 10, search: search || undefined, serviceId: serviceId || undefined, status: status === 'ALL' ? undefined : status }), api.services.list({ page: 1, limit: 50 })]); const enriched = await Promise.all(monitors.data.map(async (monitor) => { if (monitor.latestCheck) return monitor; try { return { ...monitor, latestCheck: await api.checkResults.latest(monitor.id) }; } catch { return monitor; } })); setItems(enriched); setMeta(monitors.meta); setServices(serviceData.data); if (createService && !serviceData.data.some((service) => service.id === createService)) setCreateService(''); setError(''); } catch (err) { setError(err instanceof Error ? err.message : 'Impossible de charger les monitors.'); } }, [page, search, serviceId, status, createService]);
  useEffect(() => { supabase.auth.getUser().then(({ data }) => { if (!data.user) window.location.href = '/login'; else void load(); }); }, [load]);
  async function create(event: FormEvent) { event.preventDefault(); if (!createService || !name.trim() || !url.trim()) return; setBusy(true); setError(''); try { await api.monitors.create({ serviceId: createService, name: name.trim(), url: url.trim(), interval, timeout: 10000, expectedStatus: 200 }); setName(''); setUrl(''); setInterval(300); setCreateService(''); setPage(1); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Création impossible.'); } finally { setBusy(false); } }
  async function toggle(item: Monitor) { try { if (item.isActive) await api.monitors.deactivate(item.id); else await api.monitors.activate(item.id); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Modification impossible.'); } }
  function remove(item: Monitor) { setConfirm(item); }
  async function confirmRemove() { if (!confirm) return; setBusy(true); try { await api.monitors.remove(confirm.id); setConfirm(null); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Suppression impossible.'); } finally { setBusy(false); } }
  const dot = (item: Monitor) => !item.isActive ? 'bg-[var(--solar)]' : item.latestCheck?.status === 'DOWN' ? 'bg-[var(--flare)]' : item.latestCheck?.status === 'UP' ? 'bg-[var(--volt)]' : 'bg-white/25';
  return <div className="mx-auto max-w-6xl px-4 py-7 sm:px-6 sm:py-10 lg:px-8"><div className="mb-7"><p className="data-mono text-xs uppercase tracking-[0.18em] text-[var(--electric)]">Workspace / Monitors</p><h1 className="mt-2 text-3xl font-bold">Monitors</h1><p className="mt-2 text-sm text-white/45">Recherchez, filtrez et pilotez tous vos endpoints depuis un seul endroit.</p></div>{error && <div className="mb-5 rounded-xl border border-[var(--flare)]/20 bg-[var(--flare)]/10 px-4 py-3 text-sm text-[var(--flare)]">{error}</div>}
    <section className="rounded-2xl border border-white/[0.07] bg-white/[0.025] p-5 sm:p-6"><p className="data-mono text-xs uppercase tracking-[0.15em] text-white/30">Nouveau monitor</p><form onSubmit={create} className="mt-4 grid gap-3 md:grid-cols-[180px_1fr_1.5fr_180px_auto]"><select required value={createService} onChange={(e) => setCreateService(e.target.value)} className="auth-input"><option value="" disabled>Sélectionner un service…</option>{services.map((service) => <option key={service.id} value={service.id}>{service.name}</option>)}</select><input required value={name} onChange={(e) => setName(e.target.value)} placeholder="Nom du monitor" className="auth-input" /><input required type="url" value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://api.exemple.com/health" className="auth-input" /><div><select value={interval} onChange={(e) => setInterval(Number(e.target.value))} className="auth-input"><option value={60}>1 minute</option><option value={300}>5 minutes — recommandé</option><option value={600}>10 minutes</option><option value={900}>15 minutes</option><option value={1800}>30 minutes</option><option value={3600}>1 heure</option></select><p className="mt-1.5 text-[10px] leading-4 text-white/35">1 min = critique · 1 h = disponibilité générale</p></div><button disabled={busy || !createService} className="auth-button md:w-auto">{busy ? 'Ajout…' : 'Ajouter'}</button></form></section>
    <section className="mt-5 rounded-2xl border border-white/[0.07] bg-white/[0.025] p-5 sm:p-6"><div className="grid gap-3 lg:grid-cols-[1fr_190px_170px]"><input value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} placeholder="Rechercher nom ou URL…" className="auth-input" /><select value={serviceId} onChange={(e) => { setServiceId(e.target.value); setPage(1); }} className="auth-input"><option value="">Tous les services</option>{services.map((service) => <option key={service.id} value={service.id}>{service.name}</option>)}</select><select value={status} onChange={(e) => { setStatus(e.target.value as Filter); setPage(1); }} className="auth-input"><option value="ALL">Tous les statuts</option><option value="UP">UP</option><option value="DOWN">DOWN</option><option value="PAUSED">En pause</option></select></div><div className="mt-5 space-y-2">{items.map((item) => <Link href={`/dashboard/monitors/${item.id}`} key={item.id} className="block rounded-xl border border-white/[0.07] bg-[var(--ink)] p-4 transition hover:border-[var(--electric)]/25"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex items-center gap-3"><span className={`h-2.5 w-2.5 shrink-0 rounded-full ${dot(item)}`} /><div><h3 className="font-semibold">{item.name}</h3><p className="data-mono mt-1 break-all text-xs text-white/35">{item.url}</p></div></div></div><div className="flex flex-wrap items-center gap-2"><span className="data-mono rounded-md bg-white/[0.04] px-2 py-1 text-[10px] text-white/40">GET · {formatInterval(item.interval)}</span><button type="button" onClick={(event) => { event.preventDefault(); void toggle(item); }} className="rounded-lg border border-white/10 px-3 py-2 text-xs text-white/65 hover:text-white">{item.isActive ? 'Pause' : 'Reprendre'}</button><button type="button" onClick={(event) => { event.preventDefault(); remove(item); }} className="rounded-lg border border-[var(--flare)]/15 px-3 py-2 text-xs text-[var(--flare)] hover:bg-[var(--flare)]/10">Supprimer</button></div></div></Link>)}{!items.length && <p className="py-10 text-center text-sm text-white/30">Aucun monitor trouvé.</p>}</div><Pagination meta={meta} page={page} setPage={setPage} /></section>{confirm && <ConfirmDialog item={confirm} busy={busy} onCancel={() => { if (!busy) setConfirm(null); }} onConfirm={() => void confirmRemove()} />}</div>;
}
function Pagination({ meta, page, setPage }: { meta: PaginationMeta; page: number; setPage: (page: number) => void }) { if (meta.totalPages <= 1) return null; return <div className="mt-5 flex items-center justify-between border-t border-white/[0.06] pt-4"><span className="data-mono text-[10px] text-white/30">Page {page} / {meta.totalPages}</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => setPage(page - 1)} className="rounded-lg border border-white/10 px-3 py-2 text-xs disabled:opacity-30">←</button><button disabled={page >= meta.totalPages} onClick={() => setPage(page + 1)} className="rounded-lg border border-white/10 px-3 py-2 text-xs disabled:opacity-30">→</button></div></div>; }
